### ISSUE TITLE
Invalid literal for Decimal

### ISSUE THREAD

**Issue by KevinHanson** [ctsit/nacculator#37]
When processing follow-up visit packets any time there is data typed in the free text field fu_othcondx NACCulator raises the error:

Traceback (most recent call last):
  File "./nacc/redcap2nacc.py", line 209, in <module>
    main()
  File "./nacc/redcap2nacc.py", line 197, in main
    warnings += check_blanks(packet)
  File "./nacc/redcap2nacc.py", line 33, in check_blanks
    if f.blanks and not empty(f)]:
  File "./nacc/redcap2nacc.py", line 83, in empty
    return field.value.strip() == ""
  File "/Users/kevinhanson/code/nacculator/nacc/uds3/__init__.py", line 76, in value
    return self.udstype(self.val)
  File "/Users/kevinhanson/code/nacculator/nacc/uds3/__init__.py", line 37, in __call__
    decimal.Decimal(value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/decimal.py", line 547, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/decimal.py", line 3873, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: 'chronic renal insufficiency depression GDS 14'

**Comment by ufl-taeber** [comment]
Fixed with commit 68977d22c27a916ee791e1bb577a795630c5b74c.
