### ISSUE TITLE
Generator tool no longer separates fields by form

### ISSUE THREAD

**Issue by ufl-taeber** [ctsit/nacculator#96]
`tools/generator.py` used to take a set of CSVs and create Python classes for each with the appropriate fields (see 30801342e3d4ca3780769b4d2adcc36694e30a18). This is no longer the case.

**Steps to reproduce**
1. Download the IVP CSV files
```
$ mkdir ded_ivp
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedheader.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedA1IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedA2IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedA3IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedA4DIVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedA5IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB1IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB4IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB5IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB6IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB7IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB8IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedB9IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedC2IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedD1IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedD2IVP.csv
$ wget -P ./ded_ivp https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/uds3dedZ1IVP.csv
```
2. Run the old version:
```
$ git checkout 30801342e3d4ca3780769b4d2adcc36694e30a18
$ python2 tools/generator.py ./ded_ivp >ivpform-old.py
$ head -n20 ivpform-old.py
import nacc.uds3


def header_fields():
    fields = {}
    fields['PACKET'] = nacc.uds3.Field(name='PACKET', typename='Char', position=(1, 2), length=2, inclusive_range=None, allowable_values=[], blanks=[])
    fields['FORMID'] = nacc.uds3.Field(name='FORMID', typename='Char', position=(4, 6), length=3, inclusive_range=None, allowable_values=[], blanks=[])
    fields['FORMVER'] = nacc.uds3.Field(name='FORMVER', typename='Num', position=(8, 10), length=3, inclusive_range=(1, 3), allowable_values=[], blanks=[])
    fields['ADCID'] = nacc.uds3.Field(name='ADCID', typename='Num', position=(12, 13), length=2, inclusive_range=(2, 38), allowable_values=[], blanks=[])
    fields['PTID'] = nacc.uds3.Field(name='PTID', typename='Char', position=(15, 24), length=10, inclusive_range=None, allowable_values=[], blanks=[])
    fields['VISITMO'] = nacc.uds3.Field(name='VISITMO', typename='Num', position=(26, 27), length=2, inclusive_range=(1, 12), allowable_values=[], blanks=[])
    fields['VISITDAY'] = nacc.uds3.Field(name='VISITDAY', typename='Num', position=(29, 30), length=2, inclusive_range=(1, 31), allowable_values=[], blanks=[])
    fields['VISITYR'] = nacc.uds3.Field(name='VISITYR', typename='Num', position=(32, 35), length=4, inclusive_range=(2005, 2014), allowable_values=[], blanks=[])
    fields['VISITNUM'] = nacc.uds3.Field(name='VISITNUM', typename='Char', position=(37, 39), length=3, inclusive_range=None, allowable_values=[], blanks=[])
    fields['INITIALS'] = nacc.uds3.Field(name='INITIALS', typename='Char', position=(41, 43), length=3, inclusive_range=None, allowable_values=[], blanks=[])
    return fields


class FormB6(nacc.uds3.FieldBag):
    def __init__(self):
        self.fields = header_fields()
        self.fields['NOGDS'] = nacc.uds3.Field(name='NOGDS', typename='Num', position=(45, 45), length=1, inclusive_range=(0, 1), allowable_values=['9', '1', '0'], blanks=[])
        self.fields['SATIS'] = nacc.uds3.Field(name='SATIS', typename='Num', position=(47, 47), length=1, inclusive_range=(0, 1), allowable_values=['9', '1', '0'], blanks=[])
```
3. Compare that output with the new version
```
$ git checkout develop
$ python3 tools/generator.py /Users/taeber/code/ctsit/star/adrc-forms/csvs/dict_ivp 
import nacc.uds3


Traceback (most recent call last):
  File "tools/generator.py", line 194, in <module>
    main()
  File "tools/generator.py", line 162, in main
    header = generate_header(os.path.join(data_dict_path, header_file))
  File "tools/generator.py", line 96, in generate_header
    form = generate(ded)
  File "tools/generator.py", line 71, in generate
    field.type = record['Data type']
KeyError: 'Data type'
```

**What happened?**

The version in `develop` errors out and does not produce useful python code.

**What did you expect to happen?**

I expected there to be no difference.

**Comment by ufl-taeber** [comment]
Fixed with v1.0.0
